language: r
r: bioc-release
sudo: false
dist: trusty

# install R: use r-packages-precise (https://cran.r-project.org/bin/linux/ubuntu/precise/)
# as source which is white listed (https://github.com/travis-ci/apt-source-whitelist/)
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - libnetcdf-dev
    - netcdf-bin
    - libnetcdf-dev
    - libhdf5-dev
    - texlive-latex-extra

# cache local R libraries directory:
cache:
  directories:
      - ~/Rlib

# install the package and dependencies:
# - create directory for R libraries (if not already exists)
# - create .Renviron with location of R libraries
# - define R repository in .Rprofile
# - install packages

script:
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - Rscript -e 'install.packages("knitr")'
  - Rscript -e 'source("http://www.bioconductor.org/biocLite.R"); biocLite(c("pRoloc", "pRolocdata", "BiocStyle", "gridExtra"), suppressUpdates = TRUE)'
  - make
