language: bash

# use containers
sudo: false

# install R: use r-packages-precise (https://cran.r-project.org/bin/linux/ubuntu/precise/)
# as source which is white listed (https://github.com/travis-ci/apt-source-whitelist/)
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
#   - pandoc

# cache local R libraries directory:
cache:
  directories:
      - ~/Rlib

# install the package and dependencies:
# - create directory for R libraries (if not already exists)
# - create .Renviron with location of R libraries
# - define R repository in .Rprofile
# - install packages


before_script:
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - Rscript -e 'source("http://www.bioconductor.org/biocLite.R"); biocLite(c("pRoloc", "pRolocdata", "BiocStyle", "knitr", "gridExtra"), suppressUpdates = TRUE)'

script:
  - make
